### ISSUE TITLE
Unable to delete empty changesets

### ISSUE THREAD

**Issue by stevevance** [transitland/dispatcher#100]
There's a large number of empty changesets associated with David Chiles [in the dispatcher](https://transit.land/dispatcher/users/18). 

[Example changeset 1414](https://transit.land/dispatcher/changesets/1414)

I can't delete them. I clicked "Edit changeset" in order to reach the "Delete changeset" button, but nothing happens after clicking "Edit changeset".

**Comment by drewda** [comment]
@stevevance when I load https://transit.land/dispatcher/changesets/1414 I see a JSON payload for Port Authority of Allegheny County. Are you not seeing any JSON being rendered? If so, it might be worth double checking your browser's developer console. If you see 429 errors on the network requests, it's because the API proxy thinks you're making too many requests. Sometimes that can happen if you click through Dispatcher screens quickly.

**Comment by stevevance** [comment]
It works now.
